targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          generate_for: ['lib']
      freezed:freezed:
        options:
          # Options for the freezed builder
          # For example, you can set the output directory
          # output: lib/generated
