name: clinics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Routing
  go_router: ^13.0.1

  # HTTP API Client
  dio: ^5.4.0

  # Google & Facebook Sign In
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # For theme persistence (optional but recommended)
  shared_preferences: ^2.2.2

  # Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.10.0

  # Cryptography
  crypto: ^3.0.6
  equatable:
  bloc: ^8.1.4
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_staggered_animations:

  # Code Generation
  freezed_annotation: ^2.4.1
  injectable: ^2.5.1
  get_it:
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  carousel_slider_plus: ^7.1.1
  back_button_interceptor: ^7.0.3
  flutter_spinkit: ^5.2.1
  flutter_quill: ^11.4.2
  markdown_quill: ^4.3.0 
  markdown: ^7.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700